### ISSUE TITLE
how do you plan to achieve the pwa part?

### ISSUE THREAD

**Issue by silva96** [OnRailsBlog/hhnpwa#1]

**Comment by johnbeatty** [comment]
That's the next part, but it's likely going to start from the HNPWA I wrote earlier.

**Comment by johnbeatty** [comment]
Just added! Thanks for your patience!

**Comment by silva96** [comment]
Everything in this commit enables a rails app to be a PWA ?

https://github.com/OnRailsBlog/hhnpwa/commit/f82aa63f453920c3e99b7094ebfd09242a48a037

Or there's something else in your backlog?

**Comment by johnbeatty** [comment]
In terms of Google's Lighthouse test, it's a PWA. I think the current challenge is what can you do with an on device worker and offline capabilities? That's where the research needs to occur.

See my other project for another example that scores 100/100 on Google's lighthouse test: https://github.com/johnbeatty/worlds-fastest-pwa
